# -*- coding: utf-8 -*-
import datetime
import sqlite3

# Form implementation generated from reading ui file 'first_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

from main import Main


class FirstUser(QWidget):
    def __init__(self, User, auth):
        super().__init__()
        self.first_user = self
        self.User = User
        self.auth = auth

        self.setObjectName("first_user")
        self.resize(641, 674)

        self.container = QtWidgets.QLabel(self.first_user)
        self.container.setGeometry(QtCore.QRect(30, 30, 581, 621))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setUnderline(True)
        self.container.setFont(font)
        self.container.setStyleSheet("background-color: #fff; border-radius: 30px;")
        self.container.setText("")
        self.container.setObjectName("container")

        self.header = QtWidgets.QLabel(self.first_user)
        self.header.setGeometry(QtCore.QRect(40, 70, 561, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.header.setFont(font)
        self.header.setStyleSheet("background-color: #fff;")
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")

        self.email = QtWidgets.QLabel(self.first_user)
        self.email.setGeometry(QtCore.QRect(50, 180, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.email.setFont(font)
        self.email.setStyleSheet("background-color: #fff;\n"
                                 "padding: 0 10px;")
        self.email.setObjectName("email")

        self.email_edit = QtWidgets.QLineEdit(self.first_user)
        self.email_edit.setGeometry(QtCore.QRect(50, 230, 541, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(15)
        self.email_edit.setFont(font)
        self.email_edit.setStyleSheet("background-color: #fff;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"padding: 0 10px;\n"
"")
        self.email_edit.setText("")
        self.email_edit.setObjectName("email_edit")


        self.password = QtWidgets.QLabel(self.first_user)
        self.password.setGeometry(QtCore.QRect(50, 300, 531, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: #fff;\n"
"padding: 0 10px;")
        self.password.setObjectName("password")

        self.password_edit = QtWidgets.QLineEdit(self.first_user)
        self.password_edit.setGeometry(QtCore.QRect(50, 350, 541, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(15)
        self.password_edit.setFont(font)
        self.password_edit.setStyleSheet("background-color: #fff;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"padding: 0 10px;\n"
"")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")

        self.view_password = QtWidgets.QRadioButton(self.first_user)
        self.view_password.setGeometry(QtCore.QRect(70, 410, 511, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.view_password.setFont(font)
        self.view_password.setStyleSheet("background-color: #fff;\n"
"padding: 0 10px;")
        self.view_password.setIconSize(QtCore.QSize(16, 16))
        self.view_password.setObjectName("view_password")
        self.view_password.clicked.connect(self.open_password)

        self.button = QtWidgets.QPushButton(self.first_user)
        self.button.setGeometry(QtCore.QRect(100, 470, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        self.button.setFont(font)
        self.button.setStyleSheet("QPushButton#button {\n"
                                  "    background-color: black; \n"
                                  "    color: white;\n"
                                  "    border-radius: 10px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton#button:hover {\n"
                                  "    background-color: #474744;\n"
                                  "}")
        self.button.setObjectName("button")
        self.button.clicked.connect(self.authenticate)

        self.retranslateUi(self.first_user)
        QtCore.QMetaObject.connectSlotsByName(self.first_user)

    def retranslateUi(self, first_user):
        _translate = QtCore.QCoreApplication.translate
        first_user.setWindowTitle(_translate("first_user", "Form"))
        self.header.setText(_translate("first_user", "Создание первого пользователя"))
        self.email_edit.setPlaceholderText(_translate("first_user", "example@<domain>.[ru/com]"))
        self.email.setText(_translate("first_user", "Email пользователя:"))
        self.button.setText(_translate("first_user", "Войти"))
        self.password.setText(_translate("first_user", "Пароль"))
        self.view_password.setText(_translate("first_user", "Посмотреть пароль"))


    def open_password(self, event):
        if event:
            self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        else:
            self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)


    def authenticate(self):
        if self.email_edit.text().strip():
            if self.password_edit.text().strip():
                connection = sqlite3.connect('sql/example.db')
                cursor = connection.cursor()
                postgres_insert_query = """INSERT INTO users (first_name, last_name, patronymic, post, birthdate, email, passwd) 
                                            VALUES (%s, %s, %s, %s, %s, %s, %s)"""
                record_to_insert = ('Admin', 'Admin',
                                    '',
                                    'Технолог',
                                    datetime.date(2000, 1, 1), self.email_edit.text().strip(),
                                    self.password_edit.text(), '')
                cursor.execute(postgres_insert_query, record_to_insert)
                connection.commit()
                user = self.User([1, 'Admin', 'Admin', '', 'Технолог', datetime.date(2000, 1, 1), self.email_edit.text().strip(), self.password_edit.text(), ''])
                self.main_window = Main(self.db, user, self.auth)
                self.main_window.show()
                self.close()
                self.email_edit.clear()
                self.password_edit.clear()
            else:
                self.password_edit.setStyleSheet("background-color: #fff;\n"
                                              "border: 2px solid red;\n"
                                              "border-radius: 10px;\n"
                                              "padding: 0 10px;\n"
                                              "")
        else:
            self.email_edit.setStyleSheet("background-color: #fff;\n"
"border: 2px solid red;\n"
"border-radius: 10px;\n"
"padding: 0 10px;\n"
"")